export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS'
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR'

export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS'
export const CREATE_COURSE_ERROR = 'CREATE_COURSE_ERROR'