export const GET_TAB_SUCCESS = 'GET_TAB_SUCCESS'
export const GET_TAB_ERROR = 'GET_TAB_ERROR'

export const CREATE_TAB_SUCCESS = 'CREATE_TAB_SUCCESS'
export const CREATE_TAB_ERROR = 'CREATE_TAB_ERROR'