// <auto-generated />
using System;
using DbRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbRepository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20181212145834_new2")]
    partial class new2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.GuitarTab.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Model.GuitarTab.Lesson", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseID");

                    b.Property<string>("Name");

                    b.Property<int?>("TabID");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TabID");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("Model.GuitarTab.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Fret");

                    b.Property<byte>("StringNumber");

                    b.Property<int?>("TabIterationID");

                    b.HasKey("ID");

                    b.HasIndex("TabIterationID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Model.GuitarTab.Tab", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Creator");

                    b.Property<int>("GuitarType");

                    b.Property<string>("Name");

                    b.Property<double>("Tempo");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("Model.GuitarTab.TabIteration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TabID");

                    b.Property<double>("WaitTimeScalar");

                    b.HasKey("ID");

                    b.HasIndex("TabID");

                    b.ToTable("TabIteration");
                });

            modelBuilder.Entity("Model.UserModel.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Model.GuitarTab.Course", b =>
                {
                    b.HasOne("Model.UserModel.User")
                        .WithMany("Courses")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Model.GuitarTab.Lesson", b =>
                {
                    b.HasOne("Model.GuitarTab.Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseID");

                    b.HasOne("Model.GuitarTab.Tab", "Tab")
                        .WithMany()
                        .HasForeignKey("TabID");
                });

            modelBuilder.Entity("Model.GuitarTab.Note", b =>
                {
                    b.HasOne("Model.GuitarTab.TabIteration")
                        .WithMany("ActiveNotes")
                        .HasForeignKey("TabIterationID");
                });

            modelBuilder.Entity("Model.GuitarTab.Tab", b =>
                {
                    b.HasOne("Model.UserModel.User")
                        .WithMany("BoughtTabs")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Model.GuitarTab.TabIteration", b =>
                {
                    b.HasOne("Model.GuitarTab.Tab")
                        .WithMany("Iterations")
                        .HasForeignKey("TabID");
                });
#pragma warning restore 612, 618
        }
    }
}
